# pip audit for dependency scan / pip means python package installer
name: dependency scan
on:
 workflow_call:

jobs:
   dependency-check:
      runs-on: ubuntu-latest
      steps:
         - name: Code Checkout
           uses: actions/checkout@v4

         -  name: Setup Python 3.10
            uses: actions/setup-python@v4
            with:
               python-version: "3.10"

         - name: pip Install pip audit
           run: pip install pip-audit

         - name: Audit dependencies
           run: pip-audit -r requirements.txt 