name: Deploy flask App

on:
  workflow_dispatch:
jobs:
    Deploy:
         env:
           DOCKERHUB_USER : ${{ vars.DOCKERHUB_USER }}
         runs-on: self-hosted
         steps: 
         - name: Checkout Code
           uses: actions/checkout@v4

         - name: deploy with docker compose
           uses: docker compose up -d --build