name: Deploy Flask App

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: self-hosted

    env:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: docker compose up -d --build