name: Deploy Flask App

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy
        env:
          DOCKER_TAG: ${{ github.sha }}
        run: |
          docker pull sarvesh01234/github-actions-app:${DOCKER_TAG}
          export DOCKER_TAG=${DOCKER_TAG}
          docker compose down
          docker compose up -d --force-recreate
          