name: DevSecOps End to End Pipeline

on:
  push:
    branches: [main]

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secrets-scan:
    uses: ./.github/workflows/secrets-scan.yml

  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

  docker-scan:
    uses: ./.github/workflows/docker-file-scan.yml

  # build:
  #   needs: [code-quality, secrets-scan, dependency-scan, docker-scan]
  #   uses: ./.github/workflows/docker-build-push.yml
  #   secrets: inherit

  build:
    needs: [code-quality, secrets-scan, dependency-scan, docker-scan]
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit

  trivy:
    needs: [build]
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit

  deploy-dev:
    name: Deploy Dev
    needs: trivy
    runs-on: ubuntu-latest

    steps:
      - name: Clone GitOps Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/SarveshGugale/ai-bank-app-gitops-CD.git

      - name: Update Dev Image
        run: |
          cd ai-bank-app-gitops-CD

          sed -i '/- name: bankapp/{n;s|image: .*|image: sarvesh01234/ai-bankapp:${{ github.sha }}|;}' manifests/dev/deployment.yml

      - name: Commit and Push
        run: |
          cd ai-bank-app-gitops-CD

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add manifests/dev/deployment.yml

          git commit -m "Deploy Dev ${{ github.sha }}" || echo "No changes"

          git push
