name: Docker Build & push

on:
    workflow_call:
jobs:
    build-and-push:
        runs-on: ubuntu-latest 
        steps:
            
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build & push to Docker_Hub
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: |
                  ${{ vars.DOCKERHUB_USER }}/ai-bankapp:latest
                  ${{ vars.DOCKERHUB_USER }}/ai-bankapp:${{ github.sha }}
