name: docker_build_push
on:
  push:
    branches: [main]
jobs:
  build & Push:
     runs-on: ubuntu-latest

     steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-actions@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: build & push DockerHub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USER }}/github-actions-app:latest

