# It check python syntax with flake 8 libararies.
# Python linter is used for syntax issue or follow best practices

# Error we got: Process complated with exit code 1 means expected 2 lines but found 1

name: python lint

on:
  # workflow_dispatch: 
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            python-version: ["3.10","3.11","3.12","3.13","3.14"]

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
           python-version: ${{ matrix.python-version }}  # use stable version

        - name: Install dependencies
          run: |
           pip install flake8
           pip install -r requirements.txt 

        - name: Run linter
          run: flake8 app.py