name: sarvesh 

on:
  push:
    branches: [main]
jobs:
  DetailsSarvesh:
    runs-on: ubuntu-latest
    steps:  
      - name: Username of user
        run: echo "sarvesh Gugale"
      - name: University of BE Completed
        run: echo "Shivaji University,Kop"
      - name: completed year of BE
        run: echo "2029-2020"
      - name: Say thanks for update to user 
        run: echo "Hello $USER"
  
    
