# api-key, sensitive data , credentials
# Gitleaks is tool which check our git commit history and scan it check any vernabilities issues

name: secrets scan
on:
 workflow_call:

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Code
         uses: actions/checkout@v4
         with:
           fetch-depth: 0

       - name: Run Gitleaks
         uses: gitleaks/gitleaks-actions@v2
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
