name: Update GitOps Repository

on:
  workflow_dispatch:

jobs:
  update-gitops:
    runs-on: ubuntu-latest

    steps:
      - name: Clone GitOps Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/SarveshGugale/ai-bank-app-gitops-CD.git

      - name: Verify Repository
        run: |
          cd ai-bank-app-gitops-CD
          ls -R
