name: Update GitOps Repository

on:
  workflow_call:

jobs:
  update-gitops:
    runs-on: ubuntu-latest

    steps:
      - name: Clone GitOps Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/SarveshGugale/ai-bank-app-gitops-CD.git

      - name: Update Deployment Image
        run: |
          cd ai-bank-app-gitops-CD
          sed -i '/- name: bankapp/{n;s|image: .*|image: sarvesh01234/ai-bankapp:${{ github.sha }}|;}' manifests/dev/deployment.yml
         
      - name: Commit and Push Changes
        run: |
          cd ai-bank-app-gitops-CD

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add manifests/dev/deployment.yml

          git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"

          git push
